/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VillainsImport } from './routes/villains'
import { Route as TableImport } from './routes/table'
import { Route as HeroesImport } from './routes/heroes'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const AntiHeroesLazyImport = createFileRoute('/anti-heroes')()

// Create/Update Routes

const AntiHeroesLazyRoute = AntiHeroesLazyImport.update({
  path: '/anti-heroes',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/anti-heroes.lazy').then((d) => d.Route))

const VillainsRoute = VillainsImport.update({
  path: '/villains',
  getParentRoute: () => rootRoute,
} as any)

const TableRoute = TableImport.update({
  path: '/table',
  getParentRoute: () => rootRoute,
} as any)

const HeroesRoute = HeroesImport.update({
  path: '/heroes',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/heroes': {
      preLoaderRoute: typeof HeroesImport
      parentRoute: typeof rootRoute
    }
    '/table': {
      preLoaderRoute: typeof TableImport
      parentRoute: typeof rootRoute
    }
    '/villains': {
      preLoaderRoute: typeof VillainsImport
      parentRoute: typeof rootRoute
    }
    '/anti-heroes': {
      preLoaderRoute: typeof AntiHeroesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  HeroesRoute,
  TableRoute,
  VillainsRoute,
  AntiHeroesLazyRoute,
])

/* prettier-ignore-end */
